package app.typelauncher

import androidx.compose.ui.semantics.SemanticsPropertyKey

internal const val CAROUSEL_TAG = "carousel"
internal val CarouselVirtualPageKey = SemanticsPropertyKey<Int>("CarouselVirtualPage")

internal const val HOME_SCREEN_TAG = "home_screen"
internal const val WIDGETS_SCREEN_TAG = "widgets_screen"
internal const val AGENDA_SCREEN_TAG = "agenda_screen"
internal const val SEARCH_FIELD_TAG = "search_field"
internal const val APPS_CARD_TAG = "apps_card"
internal const val APPS_LIST_TAG = "apps_list"
internal const val APP_ROW_TAG = "app_row"
internal const val APP_ICON_TAG = "app_icon"
internal const val WORK_APP_BADGE_TAG = "work_app_badge"
internal const val APP_INFO_ACTION_TAG = "app_info_action"
internal const val TOGGLE_DOCK_ACTION_TAG = "toggle_dock_action"
internal const val RESET_RANK_ACTION_TAG = "reset_rank_action"
internal const val DOCK_CARD_TAG = "dock_card"
internal const val DOCK_LIST_TAG = "dock_list"
internal const val DOCK_HINT_TAG = "dock_hint"
internal const val DOCK_APP_TAG = "dock_app"
internal const val AGENDA_PERMISSION_TAG = "agenda_permission"
internal const val AGENDA_EMPTY_TAG = "agenda_empty"
internal const val AGENDA_EVENTS_TAG = "agenda_events"
internal const val ADD_WIDGET_CARD_TAG = "add_widget_card"
internal const val WIDGET_PICKER_TAG = "widget_picker"
internal const val WIDGET_PICKER_LIST_TAG = "widget_picker_list"
internal const val WIDGET_APP_HEADER_TAG = "widget_app_header"
internal const val WIDGET_PROVIDER_ROW_TAG = "widget_provider_row"
internal const val WIDGET_PREVIEW_TAG = "widget_preview"
internal const val WIDGET_CARD_TAG = "widget_card"
internal const val REMOVE_WIDGET_ACTION_TAG = "remove_widget_action"
internal const val SETTINGS_BUTTON_TAG = "settings_button"
internal const val SETTINGS_SCREEN_TAG = "settings_screen"
internal const val SETTINGS_DONE_BUTTON_TAG = "settings_done_button"
internal const val DOCK_ENABLED_SWITCH_TAG = "dock_enabled_switch"
internal const val DOCK_ICON_COUNT_SLIDER_TAG = "dock_icon_count_slider"
